update

diff --git a/trixie-mod b/trixie-mod
--- a/trixie-mod
+++ b/trixie-mod
@@ -45,7 +45,6 @@ function menu() {
         --menu "Run Options In Order:" 0 0 0 \
         "Step 1"                                "Update System" \
         "Step 2"                                "Installs Gnome & Dependencies" \
-        "Step 3"                                "Install Applications, Utilities, & Rice" \
         "Optional Nvidia Drivers"               "Do not install if on Surface kernal" \
         "Optional Surface Kernel"               "Microsoft Surface Kernal" \
         "Hyprland"                              "**Currently Broken** Install Hyprland & All Dependencies" \
@@ -99,32 +98,23 @@ while true; do
             echo -e "${GREEN}debian-maintenance.sh Copied To Home Directory${NC}"
             ;;
         "Step 2")
-            echo -e "${YELLOW}Installing Gnome...${NC}"
-                cd scripts || exit
-                chmod u+x gnomeinstall.sh
-                sudo ./gnomeinstall.sh
-                cd "$builddir" || exit
-            echo -e "${GREEN}Gnome Installed Successfully!${NC}"
-            ;;
-        "Step 3")
-            echo -e "${YELLOW}Installing Core Applications...${NC}"
-                cd scripts || exit
-                chmod u+x apps.sh
-                sudo ./apps.sh
-                cd "$builddir" || exit
-            echo -e "${GREEN}Core Apps Installed successfully!${NC}"
-            # Gimp Dots
-                echo -e "${YELLOW}Installing Piercing Gimp Presets...${NC}"
-                if git clone https://github.com/Piercingxx/gimp-dots.git; then
-                    chmod -R u+x gimp-dots
-                    chown -R "$username":"$username" gimp-dots
-                    cd ./gimp-dots || exit
-                    ./gimp-mod.sh
+            # Install Gnome and Dependencies
+                echo -e "${YELLOW}Installing Gnome...${NC}"
+                    cd scripts || exit
+                    chmod u+x gnomeinstall.sh
+                    sudo ./gnomeinstall.sh
                     cd "$builddir" || exit
-                    echo -e "${GREEN}Piercing Gimp Presets Installed Successfully!${NC}"
-                else
-                    echo -e "${RED}Failed to clone gimp-dots repository${NC}"
-                fi
+                echo -e "${GREEN}Gnome Installed Successfully!${NC}"
+            # Install Apps
+                echo -e "${YELLOW}Installing Core Applications...${NC}"
+                    cd scripts || exit
+                    chmod u+x apps.sh
+                    sudo ./apps.sh
+                    cd "$builddir" || exit
+                echo -e "${GREEN}Core Apps Installed successfully!${NC}"
+            #Apply Piercing Rice
+                echo -e "${YELLOW}Downloading and Applying PiercingXX Rice...${NC}"
+                # .config Dot Files
                 echo -e "${YELLOW}Downloading PiercingXX Dot Files...${NC}"
                     git clone https://github.com/Piercingxx/piercing-dots.git
                         chmod -R u+x piercing-dots
@@ -155,13 +145,28 @@ while true; do
                     chown -R "$username":"$username" /home/"$username"/Downloads/refs
                     cp -Rf piercing-dots/refs/* /home/"$username"/Downloads/refs
                     chown -R "$username":"$username" /home/"$username"/Downloads/refs
-                rm -rf piercing-dots
-                # Beautiful Bash  
+                    rm -Rf piercing-dots
+            # Apply Gimp Dots
+                echo -e "${YELLOW}Installing Piercing Gimp Presets...${NC}"
+                    if git clone https://github.com/Piercingxx/gimp-dots.git; then
+                        chmod -R u+x gimp-dots
+                        chown -R "$username":"$username" gimp-dots
+                        cd ./gimp-dots
+                        sudo ./gimp-mod.sh
+                        cd "$builddir" || exit
+                        rm -Rf gimp-dots
+                        echo -e "${GREEN}Piercing Gimp Presets Installed Successfully!${NC}"
+                    else
+                        echo -e "${RED}Failed to clone gimp-dots repository${NC}"
+                    fi
+            # Apply Beautiful Bash
+                echo -e "${YELLOW}Installing Beautiful Bash...${NC}"
                 git clone https://github.com/christitustech/mybash
                     chmod -R u+x mybash
                     chown -R "$username":"$username" mybash
                     cd mybash || exit
                     ./setup.sh
+                    wait
                     cd "$builddir" || exit
                     rm -rf mybash
                 echo -e "${GREEN}PiercingXX Rice Applied Successfully!${NC}"
@@ -179,6 +184,14 @@ while true; do
                 chmod u+x Surface.sh
                 sudo ./Surface.sh
                 cd "$builddir" || exit
+            ;;
+        "Cosmic"*)
+            echo -e "${YELLOW}Installing Cosmic & Dependencies...${NC}"
+                cd scripts || exit
+                chmod u+x cosmic-install.sh
+                ./cosmic-install.sh
+                cd "$builddir" || exit
+            echo -e "${GREEN}Installed successfully!${NC}"
             ;;
         "Hyprland"*)
             echo -e "${YELLOW}Installing Hyprland & Dependencies...${NC}"
